### ISSUE TITLE
Double speed with onTimeElapsed

### ISSUE THREAD

**Issue by ChristianoBolla-Appwise** [squti/Android-Wave-Recorder#13]
When you are getting the timeElapsed and you have added `waveConfig.channels = AudioFormat.CHANNEL_IN_STEREO` it make the time elapse at double speed.

This can easily be reproduced by adding this line in the Sample.
`       
 waveRecorder.waveConfig.channels = AudioFormat.CHANNEL_IN_STEREO
`

**Comment by squti** [comment]
Thanks for your report. I will work on it.

**Comment by squti** [comment]
SOLVED
