### ISSUE TITLE
Please clarify setup instructions

### ISSUE THREAD

**Issue by mavavilj** [squti/Android-Wave-Recorder#15]
I'm trying to set this project up, and I was confused about step 2 in:

https://github.com/squti/Android-Wave-Recorder#download

In which build.gradle does this belong?

Also,

https://github.com/squti/Android-Wave-Recorder#permission

is vague, since there are two AndroidManifests.

**Comment by squti** [comment]
Are you trying to use it in your own project or you are looking for the implementation in the sample project?

**Comment by mavavilj** [comment]
I'm using the sample to produce a modification.

**Comment by squti** [comment]
In the sample project, I used the `android-wave-recorder` library as a module using `implementation project(':android-wave-recorder')` in the app `build.gradle` file. You can use readme instructions to fetch the library using JitPack and remove the module and fetch it remotely. I recommend creating a new project and copy-paste the sample code and following the readme file.
