### ISSUE TITLE
Failed to resolve: com.github.squti:AndroidWaveRecorder:1.6.0

### ISSUE THREAD

**Issue by sammi06** [squti/Android-Wave-Recorder#17]
**Failed to resolve: com.github.squti:AndroidWaveRecorder:1.6.0**

I am adding library by making new project
 implementation ("com.github.squti:AndroidWaveRecorder:1.6.0") // For waveform visualization

Android Studio Hedgehog | 2023.1.1 Patch 1
dependencies {

    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")

    implementation ("com.github.squti:AndroidWaveRecorder:1.6.0") // For waveform visualization
}

**Comment by squti** [comment]
It seems the problem occures when you are using Kotlin DSL instead of Groovy in gradle. Can you check it using Groovy version of gradle?

**Comment by squti** [comment]
You forgot to put dashes in the library name.
Replace this with your implementation:
`implementation ("com.github.squti:Android-Wave-Recorder:1.6.0")`
