### ISSUE TITLE
Audio Session Id

### ISSUE THREAD

**Issue by robertlevonyan** [squti/Android-Wave-Recorder#2]
Is it possible to get the `audioSessionId` from the voice recorder?

**Comment by squti** [comment]
It's not possible for now because `audioRecorder` object is a private field without any public modifier. Why do you need `audioSessionId`?

**Comment by robertlevonyan** [comment]
I need it to visualize the voice recording process.

**Comment by squti** [comment]
Do you want it to visualize the amplitude of the user's voice?

**Comment by squti** [comment]
I will add this in the next feature update

**Comment by robertlevonyan** [comment]
Thank you!

**Comment by robertlevonyan** [comment]
Also I've noticed a thing. When pausing the recording, it is actually is stopping record the voice, but in audio file it is adding minutes of silence from paused state to resumed state. Any suggestions on how to not write this part to file?

**Comment by squti** [comment]
I will check this. Please create a different issue for your second question
