### ISSUE TITLE
 lateinit property audioRecorder has not been initialized on changeFilePath

### ISSUE THREAD

**Issue by dportuesi-wt** [squti/Android-Wave-Recorder#20]
I am trying to dynamically set my filepath based on data fetched at runtime.
I am creating my service with an empty path on create:
`private val backgroundNoiseRecorder = WaveRecorder("")`

then i have a startRecording function that will give me Ids i need to create my path. I do so like
```
val fileName = <fetched ids>
waveRecorder.configureWaveSettings {
            sampleRate = samplingRate
            channels = channelConfig
            audioEncoding = bitRate
        }
        absoluteFilePath = File(directory, fileName).absolutePath
        waveRecorder.changeFilePath(absoluteFilePath)

        waveRecorder.noiseSuppressorActive = true

        waveRecorder.startRecording()
```
However, it crashes on waveRecorder.changeFilePath(absoluteFilePath).

```
FATAL EXCEPTION: main
                                                                                                    Process: com.telus.ai.collection.debug, PID: 10583
                                                                                                    kotlin.UninitializedPropertyAccessException: lateinit property audioRecorder has not been initialized
                                                                                                    	at com.github.squti.androidwaverecorder.WaveRecorder.changeFilePath(WaveRecorder.kt:392)
...
```

This was working pre 2.0.0. Digging into the source code, changeFilePath needs to check if the waveRecorder is null or not.

**Comment by squti** [comment]
Thanks for your report. Commit https://github.com/squti/Android-Wave-Recorder/commit/6bf46fe94e0b21e83002e7c6ff598a7bdd9eb184 resolves this issue. Version `2.0.1` is now available with this bug fix.
