### ISSUE TITLE
Pause/Resume issue

### ISSUE THREAD

**Issue by robertlevonyan** [squti/Android-Wave-Recorder#3]
when I pause the recording it is stopping the record but the paused time is added to final track as a blank piece

**Comment by squti** [comment]
I checked it in the sample app and it works properly. Could you provide more information and the implementation of your code?

**Comment by robertlevonyan** [comment]
Sure.
I'm just calling `recorder?.pauseRecording()`, then `recorder?.resumeRecording()`

**Comment by squti** [comment]
I checked it and there was no problem. Did you run the sample app?
