### ISSUE TITLE
Not working with minSdk 30+

### ISSUE THREAD

**Issue by robertlevonyan** [squti/Android-Wave-Recorder#6]
The lib is not working with Scoped Storage API

**Comment by squti** [comment]
I will check this.

**Comment by robertlevonyan** [comment]
Any news?

**Comment by squti** [comment]
@abkoradiya Could you fix this?

**Comment by abkoradiya** [comment]
@robertlevonyan what issue you are facing?

**Comment by robertlevonyan** [comment]
File API is not working on Android Q+ and if target API is 30. There is a new API called scoped storage.

**Comment by abkoradiya** [comment]
> File API is not working on Android Q+ and if target API is 30. There is a new API called scoped storage.

yes we can change it using filedesriptor. till then you can use app directory using `getFilesDir()`.

**Comment by robertlevonyan** [comment]
You also have RandomAccessFile. It is also should be changed

**Comment by robertlevonyan** [comment]
any news on this?

**Comment by abkoradiya** [comment]
> any news on this?

I have created pull request. But I don't have time right now to do review changes.

**Comment by robertlevonyan** [comment]
I think you just need to merge PR and make a release, if you have already tested it :)

**Comment by abkoradiya** [comment]
> I think you just need to merge PR and make a release, if you have already tested it :)

I have already tested it. it is working. but changes are remaining which are suggested by you.

**Comment by squti** [comment]
Yes it works but unfortunately the code is not clean so I had to reject PR.

**Comment by squti** [comment]
Commit 1b78f8b4dcb1788927c01bb1710e8b2377ee1e28 resolves this issue.
