### ISSUE TITLE
Add skipSilence feature

### ISSUE THREAD

**Issue by DaChelimo** [squti/Android-Wave-Recorder#8]
This is an enhancement request. Could you kindly add the option to skip silence.

**Comment by squti** [comment]
I will consider this in future versions.

**Comment by DaChelimo** [comment]
Thanks. Amazing library = Kotlin + Small size + Flexibility 👍👍👍

**Comment by squti** [comment]
Commit a59eff8b8430dd717972586131f2e2ab5c8ac9ca resolves this issue.
